---
name: Eric
surname: Chou
position: "Data Management Analyst"
address: "Atlanta, Georgia"
# profilepic: "./img/me.jpg"
phone: 937 750 3516
email: "echou53@gmail.com"
www: "eric-chou.github.io"
github: eric-chou
linkedin: chou-eric
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
docname: Résumé
output: vitae::awesomecv
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)


packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data sctructure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative Filepaths
             ,'readr'     # Data Loading
             ,'tidyverse' # Needed for bind_rows and whatever
             ,'scholar'   # Updating publications from google scholar
             ,'kableExtra'# Adding technicalskills table
             ,'glue'
             ,'rlang'
             ,'lubridate'
            )
library(magrittr)
# Install packages not yet installed
# installed_packages <- packages %in% rownames(installed.packages())
# if (any(installed_packages == FALSE)) {
#   install.packages(packages[!installed_packages])
# }

# Packages loading
lapply(packages, library, character.only = TRUE) %>%
  invisible()
```

```{r loadData}
in_path = "../data/"

# Education
education <- read_csv(paste0(in_path,"education.csv")) %>%
  mutate(
    begin = as.Date(begin, format=("%m/%d/%y")),
    end = as.Date(end, format=("%m/%d/%y"))
  )

education.desc <- read_csv(paste0(in_path,"education_descriptions.csv"))

# Jobs
job.titles <- read_csv(paste0(in_path,"job_titles.csv")) %>%
  mutate(
    begin = as.Date(begin, format=("%m/%d/%y")),
    end = as.Date(end, format=("%m/%d/%y"))
  )

job.desc <- read_csv(paste0(in_path,"job_descriptions.csv"))

# Skills
skills <- read_csv(paste0(in_path,"skills.csv"))
```

# Education

```{r education, results="asis"}
# merge with descriptions
education %>%
  # left_join(education.desc, by=c("degree")) %>%
  arrange(desc(end)) %>%
  # format as detailed entries 
  detailed_entries(
    what=degree,
    # when=year(end),
    with=university,
    where = glue("{city}, {region}, {country}"),
    # why=accomplishments
  )
```

# Experience

```{r experience}
# exclude old jobs
job.titles.filtered <- job.titles %>%
  filter(job_id > 1)

# cut down on select bullet points
job.desc.filtered <- job.desc %>%
  # per job_id, pick desc_id's to filter out
  mutate(
    include = case_when(
      job_id == 1 ~ F,
      job_id == 2 & desc_id %in% c(1,4) ~ F,
      job_id == 3 & desc_id %in% c(NA) ~ F,
      job_id == 4 & desc_id %in% c(5) ~ F,
      TRUE ~ T
    )
  ) %>%
  filter(include == T)

job.titles.filtered %>% 
  arrange(desc(begin)) %>% 
  # Join job descriptions
  left_join(job.desc.filtered) %>% 
  # Arrange by descending begin date
  arrange(desc(begin), desc_id) %>% 
  # include department if applicable 
  mutate(
    employer = ifelse(!is.na(department), paste(employer, department, sep=", "), employer)
  ) %>%
  # Format as detailed entries
  detailed_entries(
    what = position,
    when = as.character(
      glue("{month(begin, label = TRUE, abbr = TRUE)} {year(begin)} - 
           {if_else(!is.na(end), 
           paste(month(end, label = TRUE, abbr = TRUE), year(end)), 'present')}")),
    with = employer,
    where = glue("{city}, {region}, {country}"),
    why = accomplishments) 
```

# Skills

```{r}
skills_formatted <- skills %>% 
  group_by(group_id, group) %>% 
  summarize(skills = glue_collapse(skill, sep = " $\\bullet$ ")) %>%
  arrange(group_id) %>%
  ungroup() %>%
  select(group, skills)
```

```{r, results='asis', width=40000}
for (group in skills_formatted$group) {
  cat(
    glue("\\textbf{<<tools::toTitleCase(group)>>}:", .open = "<<", .close = ">>"),
    filter(skills_formatted, group == !!group)$skills,
    "\n\n\n"
  )
}
```


# Select Publications

```{r publications}
publications <- bibliography_entries(paste0(in_path,"publications.bib")) %>% arrange(desc(issued))

# try to limit to 3
publications %>%
  filter(
    id %in% c(
      'bakshi2023multimodal',
      'chou2021designing'#,
      #'birer2020new'
    )
  )

# Full list of `r publications %>% summarize(N = n()) %>% pull(N)` publications: https://scholar.google.com/citations?user=gqYynN8AAAAJ&hl=en
```
